FROM ros:humble-ros-base-jammy

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive
ENV QT_X11_NO_MITSHM=1
ENV LANG=en_US.UTF-8
ENV ROS_DISTRO=humble
ENV ROS2_INSTALL_PATH=/opt/ros/$ROS_DISTRO
WORKDIR /ws_px4

RUN apt-get clean
RUN apt update && apt -y upgrade
RUN apt install -y --no-install-recommends 		  \
	vim udev git sudo unzip curl cmake wget tmux  \
	software-properties-common xauth xorg openbox \
	python3-argcomplete python3 python3-pip  



## Install Micro XRCE-DDS
RUN cd / && git clone https://github.com/eProsima/Micro-XRCE-DDS-Agent.git && \
	cd Micro-XRCE-DDS-Agent &&\
	mkdir build && cd build && cmake .. &&\
	make -j $(nproc) && make install && sudo ldconfig /usr/local/lib/ && \
    rm -rf build

### Build WS (px4_ros_com && px4_msgs && m-explore-ros2)
RUN mkdir -p ${WORKDIR}/src && cd ${WORKDIR}/src \
	git clone --progress --verbose -b release/1.15 https://github.com/PX4/px4_msgs.git && \
	git clone --progress --verbose https://github.com/PX4/px4_ros_com.git && \
	source /opt/ros/$ROS_DISTRO/setup.bash && cd ${WORKDIR} && colcon build

# RUN cd /px4_sim_ros2/src && git clone --progress --verbose https://github.com/robo-friends/m-explore-ros2.git
# RUN cd / && git clone --progress --verbose https://github.com/ParsaKhaledi/px4_sim_ros2.git

# RUN source /opt/ros/$ROS_DISTRO/setup.bash && cd /ws_px4_ros2/src/px4_ros_com/scripts/ && source build_ros2_workspace.bash


### Write in ~/.bashrc
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc
RUN echo "source /ws_px4_ros2/install/setup.bash" >> ~/.bashrc

### Finilize
RUN rm -rf /var/lib/apt/lists/* 