#FROM nvidia/opengl:1.0-glvnd-runtime-ubuntu20.04
FROM nvidia/opengl:1.0-glvnd-devel-ubuntu22.04

SHELL ["/bin/bash", "-c"]

ENV DEBIAN_FRONTEND=noninteractive
ENV QT_X11_NO_MITSHM=1
ENV LANG=en_US.UTF-8
ENV ROS_DISTRO=humble
ENV ROS2_INSTALL_PATH=/opt/ros/$ROS_DISTRO
WORKDIR /px4_sim_ros2

RUN apt-get clean
RUN apt update && apt -y upgrade && \
	apt install -y --no-install-recommends \
	vim udev git sudo unzip curl cmake wget tmux \
	sudo \
	gnupg2 lsb-release \
	xauth xorg openbox python3-argcomplete python3 python3-pip \
	gcc-arm-none-eabi apt-utils 

# < Directly Get source >
RUN wget https://d1uj6qtbmh3dt5.cloudfront.net/NICE-GPG-KEY && gpg --import NICE-GPG-KEY && \
        wget https://d1uj6qtbmh3dt5.cloudfront.net/2023.1/Servers/nice-dcv-2023.1-16388-ubuntu2204-x86_64.tgz && \
        tar -xvzf nice-dcv-2023.1-16388-ubuntu2204-x86_64.tgz && \
		cd nice-dcv-2023.1-16388-ubuntu2204-x86_64 && \
		apt install -y ./nice-dcv-server_2023.1.16388-1_amd64.ubuntu2204.deb

## INSTALL ROS2
RUN apt update && apt -y install locales && \
        locale-gen en_US en_US.UTF-8 && \
        update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
RUN sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null && \
        apt update &&\
        apt install -y ros-$ROS_DISTRO-desktop ros-dev-tools python3-argcomplete && \
		rosdep init && rosdep update

### Install Gazebo and some Reqs
RUN wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg && \
	echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | \ 
	sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null && \
	apt update && apt install -y \
	gz-harmonic ros-${ROS_DISTRO}-ros-gzharmonic 

## PX4 Stuff
RUN cd / && wget -O PX4-Autopilot.zip  https://github.com/PX4/PX4-Autopilot/archive/refs/tags/v1.14.3.zip && \
	unzip PX4-Autopilot.zip &&  rm -f ./PX4-Autopilot.zip && mv ./PX4-Autopilot-1.14.3 ./PX4-Autopilot 

## Install Nav2 and rtabmap
# RUN apt install -y  \
# 	ros-$ROS_DISTRO-navigation2 \
# 	ros-$ROS_DISTRO-nav2-bringup \
# 	ros-$ROS_DISTRO-rtabmap-ros 
# 	# ros-$ROS_DISTRO-gazebo*

## Install Micro XRCE-DDS
RUN cd / && git clone https://github.com/eProsima/Micro-XRCE-DDS-Agent.git
RUN cd /Micro-XRCE-DDS-Agent &&\
	mkdir build && cd build && cmake .. &&\
	make && make install && sudo ldconfig /usr/local/lib/ &&\
	cd / 
	
RUN pip3 install -U pyros-genmsg setuptools


### Build WS (px4_ros_com && px4_msgs && m-explore-ros2)
RUN mkdir -p /ws_px4/src
RUN cd /ws_px4/src && git clone --progress --verbose https://github.com/PX4/px4_msgs.git
RUN cd /ws_px4/src && git clone --progress --verbose https://github.com/PX4/px4_ros_com.git
RUN source /opt/ros/$ROS_DISTRO/setup.bash && cd /ws_px4 && colcon build

# RUN source /opt/ros/$ROS_DISTRO/setup.bash && cd /ws_px4_ros2/src/px4_ros_com/scripts/ && source build_ros2_workspace.bash

### Tumux conf
RUN cd ~ && git clone https://github.com/gpakosz/.tmux.git &&\
	ln -s -f .tmux/.tmux.conf &&\
	cp .tmux/.tmux.conf.local . &&\
	echo "set -g mouse on" >> ~/.tmux.conf 

### Write in ~/.bashrc
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc
RUN echo "source /ws_px4/install/setup.bash" >> ~/.bashrc

### Finilize
RUN rm -rf /var/lib/apt/lists/* 