ARG ROS_DISTRO=jazzy
ARG PX4_VERSION=1.17.0
ARG XRCE_AGENT_VERSION=v2.4.3
FROM nvidia/cuda:12.9.2-cudnn-devel-ubuntu24.04

LABEL maintainer="Parsa Khaledi <pa.aerospace@gmail.com>"

SHELL ["/bin/bash", "-c"]

ARG ROS_DISTRO
ENV ROS_DISTRO=${ROS_DISTRO}

ARG USER_NAME=px4
ARG USER_UID=1000
ARG USER_GID=1000
# Keep the comment off the ARG line. Docker would otherwise bake it into the value.
ARG OPENCV_VERSION=4.11.0
ARG WITH_CUDA_OPENCV=0
# Desktop defaults: 8.6 (RTX 30xx), 8.9 (RTX 40xx). PTX lets newer GPUs JIT.
ARG CUDA_ARCH_BIN=8.6;8.9
ARG CUDA_ARCH_PTX=8.9
ARG QGC_URL=https://d176tv9ibo4jno.cloudfront.net/latest/QGroundControl-x86_64.AppImage


ENV PATH="/usr/local/cuda/bin:${PATH}"
ENV LD_LIBRARY_PATH="/usr/local/cuda/lib64:${LD_LIBRARY_PATH}"
ENV DEBIAN_FRONTEND=noninteractive
ENV QT_X11_NO_MITSHM=1
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
ENV PATH="/root/.local/bin:$PATH"
# ENV ROS2_INSTALL_PATH=/opt/ros/$ROS_DISTRO
ENV HOME=/home/${USER_NAME}
ENV WORKDIR=${HOME}/ws_px4

ENV USER=${USER_NAME}
ENV PATH=${HOME}/.local/bin:${PATH}
# Ubuntu 24.04 is Python 3.12. A python3.10 path never sees the CUDA bindings.
ENV PYTHONPATH=/usr/local/lib/python3.12/site-packages

WORKDIR ${WORKDIR}

RUN apt-get clean
RUN apt update 1>/dev/null && \
	apt install -y --no-install-recommends \
	vim udev git sudo unzip curl cmake make wget tmux build-essential\
	gnupg2 lsb-release iputils-ping\
	gstreamer1.0-libav gstreamer1.0-gl python3-gi python3-gst-1.0 libpulse-mainloop-glib0 \
	libfuse2 libxcb-xinerama0 libxkbcommon-x11-0 libxcb-cursor-dev \
	fuse libx11-6 libgtk-3-dev  libglu1-mesa libopenjp2-7-dev \
	libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-base1.0-dev \
	libgstreamer-plugins-base1.0-dev \
	pkg-config libgtk-3-dev libavcodec-dev libavformat-dev  libswscale-dev \
    libv4l-dev libxvidcore-dev libx264-dev libjpeg-dev libpng-dev libtiff-dev \
    gfortran openexr libatlas-base-dev \
	libfuse2 libxcb-xinerama0 libxkbcommon-x11-0 libxcb-cursor-dev \
	xauth xorg openbox x11-utils \
	python3 python3-argcomplete python3-pip python3-dev python3-yaml \
	libcanberra-gtk-module libeigen3-dev libgflags-dev libgoogle-glog-dev\
	gcc-arm-none-eabi apt-utils  1>/dev/null
	
### Create User
# The CUDA base image already has uid 1000. Reuse that slot so bind mounts match the host.
RUN if getent passwd "${USER_UID}" >/dev/null; then userdel -r "$(getent passwd "${USER_UID}" | cut -d: -f1)"; fi && \
    if getent group "${USER_GID}" >/dev/null; then groupdel "$(getent group "${USER_GID}" | cut -d: -f1)"; fi && \
    groupadd ${USER_NAME} --gid ${USER_GID} && \
    useradd -l -m ${USER_NAME} -u ${USER_UID} -g ${USER_GID} -s /bin/bash && \
	echo "${USER_NAME} ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/${USER_NAME} && \
	mkdir -p ${WORKDIR} && \
	chmod 0440 /etc/sudoers.d/${USER_NAME} && chown -R ${USER_NAME}:${USER_NAME} ${HOME}

	### Install NICE DCV for high performance stream
# RUN cd ${WORKDIR} && \
# 	wget https://d1uj6qtbmh3dt5.cloudfront.net/NICE-GPG-KEY && gpg --import NICE-GPG-KEY && \
#     wget https://d1uj6qtbmh3dt5.cloudfront.net/2023.1/Servers/nice-dcv-2023.1-16388-ubuntu2204-x86_64.tgz && \
# 	tar -xvzf nice-dcv-2023.1-16388-ubuntu2204-x86_64.tgz && \
# 	cd nice-dcv-2023.1-16388-ubuntu2204-x86_64 && \
# 	apt install -y ./nice-dcv-server_2023.1.16388-1_amd64.ubuntu2204.deb 1>/dev/null

# rtabmap and cv_bridge link Ubuntu's libopencv. A second OpenCV in /usr/local
# is an ABI trap, so the CUDA build is opt-in (WITH_CUDA_OPENCV=1).
RUN if [ "${WITH_CUDA_OPENCV}" != "1" ]; then \
      echo "Skipping CUDA OpenCV; ROS packages use the distro libopencv."; \
    else \
      mkdir -p ${HOME}/OPENCV && cd ${HOME}/OPENCV && \
      curl -L https://github.com/opencv/opencv/archive/${OPENCV_VERSION}.zip -o opencv-${OPENCV_VERSION}.zip && \
      curl -L https://github.com/opencv/opencv_contrib/archive/${OPENCV_VERSION}.zip -o opencv_contrib-${OPENCV_VERSION}.zip && \
      unzip opencv-${OPENCV_VERSION}.zip 1>/dev/null && unzip opencv_contrib-${OPENCV_VERSION}.zip 1>/dev/null && \
      rm opencv-${OPENCV_VERSION}.zip opencv_contrib-${OPENCV_VERSION}.zip && \
      cd opencv-${OPENCV_VERSION} && \
      mkdir release && cd release && \
      cmake -D CMAKE_BUILD_TYPE=Release \
        -D CMAKE_INSTALL_PREFIX=/usr/local \
        -D WITH_CUDA=ON \
        -D WITH_CUDNN=ON \
        -D WITH_CUBLAS=ON \
        -D OPENCV_DNN_CUDA=ON \
        -D CUDA_ARCH_BIN="${CUDA_ARCH_BIN}" \
        -D CUDA_ARCH_PTX="${CUDA_ARCH_PTX}" \
        -D OPENCV_GENERATE_PKGCONFIG=ON \
        -D WITH_GSTREAMER=ON \
        -D WITH_LIBV4L=ON \
        -D ENABLE_FAST_MATH=1 \
        -D CUDA_FAST_MATH=1 \
        -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-${OPENCV_VERSION}/modules \
        -D BUILD_EXAMPLES=OFF \
        -D BUILD_opencv_python3=ON \
        -D BUILD_opencv_python2=OFF \
        -D PYTHON_EXECUTABLE=/usr/bin/python3 \
        -D BUILD_TESTS=OFF \
        -D BUILD_PERF_TESTS=OFF \
        -D CMAKE_INSTALL_PREFIX=/usr/local .. && \
      make -j5 && \
      sudo make install && \
      sudo ldconfig && \
      cd ${HOME}/ && rm -rf OPENCV; \
    fi

### INSTALL ROS2 and Nav2
RUN apt update 1>/dev/null && apt -y install locales --no-install-recommends && \
        locale-gen en_US.UTF-8 && \
        update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 1>/dev/null && \
	sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null && \
    apt update 1>/dev/null &&\
    apt install -y --no-install-recommends \
		ros-$ROS_DISTRO-ros-base \
	    ros-$ROS_DISTRO-tf2-eigen \
		ros-$ROS_DISTRO-rclcpp \
		ros-$ROS_DISTRO-rmw-cyclonedds-cpp \
		ros-$ROS_DISTRO-rviz2* \
		ros-$ROS_DISTRO-rqt \
		ros-$ROS_DISTRO-rqt-image-view ros-$ROS_DISTRO-rqt-graph \
		ros-$ROS_DISTRO-rqt-topic      ros-$ROS_DISTRO-rqt-tf-tree \
		ros-dev-tools 1>/dev/null && \
	rosdep init && rosdep update 

### Install Nav2 and rtabmap
RUN apt install -y  --no-install-recommends  \
		ros-$ROS_DISTRO-rmw-cyclonedds-cpp \
		ros-$ROS_DISTRO-navigation2 \
		ros-$ROS_DISTRO-nav2-bringup \
		ros-$ROS_DISTRO-rtabmap-ros 1>/dev/null

### Install GZ and some Reqs
RUN wget https://packages.osrfoundation.org/gazebo.gpg -O /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg && \
	echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | \
	sudo tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null && \
	apt update && apt install -y --no-install-recommends\
	gz-harmonic ros-${ROS_DISTRO}-ros-gz 1>/dev/null

# Root steps above use HOME=/home/px4; restore ownership before switching user.
RUN chown -R ${USER_NAME}:${USER_NAME} ${HOME}
	
# # Change user
USER ${USER_NAME}
WORKDIR ${WORKDIR}

### Install Qground
RUN sudo usermod -a -G dialout root && sudo usermod -a -G dialout px4 && sudo apt remove modemmanager -y &&\
	cd ${HOME} && wget -O QGroundControl.AppImage "${QGC_URL}" &&\
	chmod +x ./QGroundControl.AppImage 

### PX4 Setup
# RUN cd ${HOME} && git clone https://github.com/PX4/PX4-Autopilot.git -b v1.17.0 --recursive 1>/dev/null && \
# 	cd ${HOME}/PX4-Autopilot && sudo ./Tools/setup/ubuntu.sh 1>/dev/null

### PX4 Setup
ARG PX4_VERSION
LABEL org.opencontainers.image.source="https://github.com/ParsaKhaledi/px4_sim_ros2" \
      org.opencontainers.image.version="${PX4_VERSION}"
RUN cd ${HOME} && git clone https://github.com/PX4/PX4-Autopilot.git -b v${PX4_VERSION} --recursive \
	--progress 1>/dev/null && \
	cd ${HOME}/PX4-Autopilot && ./Tools/setup/ubuntu.sh --no-sim-tools 1>/dev/null

### Install Micro XRCE-DDS
ARG XRCE_AGENT_VERSION
RUN cd ${HOME} && git clone https://github.com/eProsima/Micro-XRCE-DDS-Agent.git -b ${XRCE_AGENT_VERSION} && \
	cd ${HOME}/Micro-XRCE-DDS-Agent &&\
	mkdir build && cd build && cmake .. -DUAGENT_P2P_PROFILE=OFF &&\
	make 1>/dev/null && sudo make install 1>/dev/null && sudo ldconfig /usr/local/lib/ &&\
	cd ${HOME} && rm -rf ${HOME}/Micro-XRCE-DDS-Agent/build 1>/dev/null

### Build WS (px4_ros_com && px4_msgs)
ARG PX4_VERSION
RUN mkdir -p ${WORKDIR}/src && \
	cd ${WORKDIR}/src && pip3 install --user --break-system-packages \
	pyros-genmsg setuptools numpy kconfiglib future jinja2 jsonschema && \
	git clone --depth 1 -b v${PX4_VERSION} https://github.com/PX4/px4_msgs.git 1>/dev/null && \
	git clone --depth 1 https://github.com/PX4/px4_ros_com.git 1>/dev/null && \
	source /opt/ros/$ROS_DISTRO/setup.bash && cd ${WORKDIR} && colcon build

### Publish distance_sensor, then build PX4 so the DDS client includes it.
COPY --chown=${USER_NAME}:${USER_NAME} includes/gz/patch_dds_topics.py /tmp/patch_dds_topics.py
RUN python3 /tmp/patch_dds_topics.py ${HOME}/PX4-Autopilot/src/modules/uxrce_dds_client/dds_topics.yaml \
	&& cd ${HOME}/PX4-Autopilot && make check_px4_sitl_default

### Tumux conf
RUN echo "set -g mouse on" >> ~/.tmux.conf 

### Write in ~/.bashrc
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc && \
	echo "source ${WORKDIR}/install/setup.bash" >> ~/.bashrc

### Finilize

WORKDIR ${WORKDIR}
