name: Docker Image CI

on:
  push:
    paths:
      - 'dockerFile/Dockerfile_px4_sim_with_GPU'
      - 'dockerFile/Dockerfile_px4_sim_NO_GPU'
    # branches: [ "docker" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  Registery: docker.io
  ImageName: alienkh/px4_sim
  ImageTag: 1.15.1_${{ github.run_number }}

jobs:
  build_and_push_docker_image_gpu:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'dockerFile/Dockerfile_px4_sim_with_GPU')
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.Registery }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push docker image with GPU
        id: build-and-push-GPU
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.Registery }}/${{ env.ImageName }}:${{ env.ImageTag }}
          file: ./dockerFile/Dockerfile_px4_sim_with_GPU

  build_and_push_docker_image_no_gpu:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'dockerFile/Dockerfile_px4_sim_NO_GPU')
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.Registery }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and Push docker image without GPU
        id: build-and-push-NoGPU
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.Registery }}/${{ env.ImageName }}:${{ env.ImageTag }}
          file: ./dockerFile/Dockerfile_px4_sim_NO_GPU
