name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  Registery: docker.io
  ImageName: alienkh/px4_sim
  ImageTag: 1.${{ github.run_number }}

jobs:

  build_and_push_docker_image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registery: ${{ env.Registery }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Extract Docker metadata
      #   id: meta
      #   uses: docker/metadata-action@v1
      #   with:
      #     images: ${{ env.Registery }}/${{ env.ImageName }}

      - name: Build and Push docker image
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          # push:   ${{ github.event_name != 'pull_request' }}
          push: true
          tags:   ${{ env.Registery }}/${{ env.ImageName }}:${{ env.ImageTag }}
          # labels: ${{ steps.meta.outputs.labels }}
