name: Docker Image CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

env:
  Registery: docker.io
  ImageName: alienkh/px4_sim
  ImageTag: 1.${{ github.run_number }}

jobs:

  build_and_push_docker_image:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.Registery }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push docker image for NO-GPU
        id: build-and-push-NoGPU
        uses: docker/build-push-action@v2
        with:
          # push:   ${{ github.event_name != 'pull_request' }}
          push: true
          tags:   ${{ env.Registery }}/${{ env.ImageName }}:dev_noGPU_${{ env.ImageTag }}
          file: ./dockerFile/Dockerfile_px4_sim_NO_GPU
          # labels: ${{ steps.meta.outputs.labels }}
      - name: Build and Push docker image with GPU
        id: build-and-push-WitGPU
        uses: docker/build-push-action@v2
        with:
          # push:   ${{ github.event_name != 'pull_request' }}
          push: true
          tags:   ${{ env.Registery }}/${{ env.ImageName }}:dev_withGPU_${{ env.ImageTag }}
          file: ./dockerFile/Dockerfile_px4_sim_with_GPU
          # labels: ${{ steps.meta.outputs.labels }}